imports_granularity = "Module"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
combine_control_expr = false
condense_wildcard_suffixes = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
hard_tabs = true
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
